myblog2024010/filterapp/urls.py
from django.contrib import admin
from django.urls import path
from filterapp import views as filter_views  # 导入你的视图函数
from django.views.generic import TemplateView

app_name = 'filterapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('filter/index', filter_views.index_view, name='index'),
    # path('filter/add_filter_info/', filter_views.add_filter_info, name='add_filter_info'),  # 指定视图函数
    path('filter/success/', filter_views.success, name='success'),
    # path('delete/<int:filter_id>/', filter_views.delete_filter, name='delete_filter'),
    # path('filter/edit_index_etl/<int:index_etl_id>/', filter_views.edit_index_etl, name='edit_index_etl'),

    # 添加信息的 URL
    path('filter/add/', filter_views.add_or_edit_info, name='add_info'),

    # 编辑信息的 URL，需要传递一个参数 index_id
    path('filter/edit/<int:index_id>/', filter_views.add_or_edit_info, name='edit_info'),

    path('filter/success/<int:index_id>/', filter_views.delete_info, name='delete_info'),

    path('filter/convert_sql/', filter_views.display_table_info, name='display_table_info'),
    path('filter/about/', filter_views.about, name='about'),
    path('filter/a/', filter_views.a_view, name='a_view'),
    path('filter/b/', filter_views.b_view, name='b_view'),
    path('filter/convert_sql/', filter_views.submit_table_info, name='submit_table_info'),
    path('filter/process_ddl/', filter_views.process_ddl, name='process_ddl'),
    # path('filter/hive_table/', filter_views.col_info, name='col_info'),
]

myblog2024010/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('filter/', include('filterapp.urls')),
    # 包含你的应用程序 URL 配置
]

myblog2024010/filterapp/models.py
from django.db import models
from django.contrib.auth.models import User

class index_etl(models.Model):
    id = models.AutoField(primary_key=True)
    index_no = models.CharField(max_length=100)
    index_name = models.CharField(max_length=100)  # 添加来源表字段
    dep_info = models.CharField(max_length=100)  # 分组字段
    sql_info = models.TextField()  # 过滤条件
    # 添加自增长的ID字段


class col_type_mapping(models.Model):
    id = models.AutoField(primary_key=True)
    mysql_col_type = models.CharField(max_length=100)
    map_col_type = models.CharField(max_length=100)



class TableInfo(models.Model):
    table_name = models.CharField(max_length=100)
    column_name = models.CharField(max_length=100)
    column_type = models.CharField(max_length=100, null=True)  # 允许为NULL
    column_length = models.IntegerField(null=True, blank=True)
    hive_column_type = models.CharField(max_length=100)
    primary_key = models.IntegerField(default=0)
    partition_key = models.IntegerField(default=0)

myblog2024010/filterapp/forms.py
from django import forms
from .models import index_etl
from .models import TableInfo

class index_etlForm(forms.ModelForm):
    class Meta:
        model = index_etl
        fields = ['id','index_no', 'index_name', 'dep_info', 'sql_info']


class InputForm(forms.Form):
    input1 = forms.CharField(label='Input 1', max_length=100)
    input2 = forms.CharField(label='Input 2', max_length=100)
    input3 = forms.CharField(label='Input 3', max_length=100)
    input4 = forms.CharField(label='Input 4', max_length=100)
    textarea = forms.CharField(label='Textarea', widget=forms.Textarea)
    checkbox = forms.BooleanField(label='Checkbox')
    dropdown = forms.ChoiceField(label='Dropdown', choices=[('option1', 'Option 1'), ('option2', 'Option 2')])

class MySQLDDLForm(forms.Form):
    ddl_statement = forms.CharField(widget=forms.Textarea)

myblog2024010/filterapp/views.py
from django.shortcuts import render, redirect
from .forms import index_etlForm
from .forms import InputForm
from .models import index_etl
import sqlparse
from .forms import MySQLDDLForm
from .models import TableInfo

from .models import col_type_mapping
from django.http import HttpResponse
from django.http import JsonResponse
from django.utils.http import urlencode
import re

def index_view(request):
    return render(request, 'index.html')

# def add_filter_info(request):
#     if request.method == 'POST':
#         form = index_etlForm(request.POST)
#         if form.is_valid():
#             form.save()
#             # 可以在这里拼凑SQL语句，并将其保存到数据库
#             # 例如：构建SQL语句并执行
#             # sql_statement = "INSERT INTO table_name (column1, column2, ...) VALUES (value1, value2, ...)"
#             return redirect('filterapp:success') # return redirect('success') # 重定向到成功页面
#     else:
#         form = index_etlForm()
#     return render(request, 'add_filter_info.html', {'form': form})

def success(request):
    etl_info_list = index_etl.objects.all()  # 获取所有的过滤器信息

    success_message = request.GET.get('success_message')
    error_message = request.GET.get('error_message')
    return render(request, 'success.html', {'etl_info_list': etl_info_list,'success_message': success_message, 'error_message': error_message})


def add_or_edit_info(request, index_id=None):
    if index_id:
        is_edit = True
        try:
            index_etl_obj = index_etl.objects.get(id=index_id)
        except index_etl.DoesNotExist:
            return HttpResponseNotFound("指定的指标不存在")
    else:
        is_edit = False
        index_etl_obj = None

    if request.method == 'POST':
        form = index_etlForm(request.POST, instance=index_etl_obj)
        if form.is_valid():
            index_etl_obj = form.save(commit=False)  # 保存表单数据但不提交到数据库
            # 在这里设置其他字段（如果有需要的话）
            index_etl_obj.save()  # 手动提交到数据库
            return redirect('filterapp:success')  # 假设你有一个名为 success 的URL模式
    else:
        form = index_etlForm(instance=index_etl_obj)
    return render(request, 'edit_index.html', {'index_etl_obj': index_etl_obj, 'form': form})


def delete_info(request, index_id):
    error_message = ''  # 初始化 error_message
    success_message = ''  # 初始化 success_message
    try:
        # 根据 index_id 获取要删除的记录
        info = index_etl.objects.get(id=index_id)
        # 删除记录
        info.delete()
        success_message = '删除成功'
    except index_etl.DoesNotExist:
        error_message = '记录不存在'

    return redirect('filterapp:success')


def extract_table_info(sql):
    table_name_match = re.search(r'CREATE TABLE `?(\w+)`?', sql)
    table_name = table_name_match.group(1) if table_name_match else ''

    fields_match = re.findall(r'`?(\w+)`?\s+(\w+)(?:\((\d+)\))?(?:\s+(PRIMARY KEY|FOREIGN KEY|UNIQUE|NOT NULL|AUTO_INCREMENT))?', sql)

    print("Fields matched:", fields_match)  # Add this line for debugging

    # Filter out items where name is "CREATE"
    table_info = [{'name': name, 'type': type_, 'length': length if length else '', 'constraint': constraint if constraint else ''}
                  for name, type_, length, constraint in fields_match if name.lower() != 'create']

    print("Table info:", table_info)  # Add this line for debugging

    return table_name, table_info

def display_table_info(request):
    mysql_sql = ''
    source_system = ''
    partition_info = ''
    table_info = []
    # primary_keys = []
    table_name = ''
    col_map = [
        ["Data 1", "Data 2"],
        ["VARCHAR", "string"],
        ["int", "bigint"],
        ["number", "bigint"]
    ]

    if request.method == 'POST':
        mysql_sql = request.POST.get('mysql_sql', '')
        partition_info = request.POST.get('partition_info', '')
        table_location = request.POST.get('table_location', '')
        # primary_keys = request.POST.getlist('primary_key[]')
        source_system = request.POST.get('source_system', '')
    else:
        mysql_sql = 'CREATE TABLE example_table (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), age INT)'

    table_name, table_info = extract_table_info(mysql_sql)

    # col_map_dict = {item[0].lower(): item[1] for item in col_map[1:]}  # 忽略第一行，因为第一行是标题行
    col_map_dict = {}
    for item in col_map[1:]:
        # 将每个元素的两个值都转换为小写
        col_map_dict[item[0].lower()] = item[1].lower()

    # 根据 table_info 中的 type 列去匹配 col_map 中的第一列，然后将对应的第二列内容添加到 table_info 中的一个新列 hive_col
    for col_info in table_info:
        type_lower = col_info['type'].lower()
        col_info['hive_col'] = col_map_dict.get(type_lower, '')

    return render(request, 'con_index.html',
                  {'mysql_sql': mysql_sql, 'table_name': table_name, 'table_info': table_info,'col_map': col_map,'source_system': source_system,'partition_info': partition_info})

def submit_table_info(request):
    primary_keys = []
    if request.method == 'POST':
        # 处理表单提交数据的逻辑...
        imary_keys = request.POST.getlist('primary_key[]')
        # 处理完毕后返回一个响应
        return render(request, 'con_index.html',{'primary_keys': primary_keys})  # 渲染一个成功提交的页面

    else:
        return HttpResponse('只允许 POST 请求！')

def about(request):
    col_Data = [
        ["Data 1", "Data 2"],
        ["Another Data 1", "Another Data 2"],
        ["A其他1", "A其他2"],
        ["A其他1", "A其他2"],
        ["A其他1", "A其他2"],
        ["A其他1", "A其他2"],
        ["VARCHAR", "string"]
    ]
    return render(request, 'about.html',{'col_Data': col_Data})

def a_view(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            # 处理表单提交的数据
            data = urlencode({
                'input1': form.cleaned_data['input1'],
                'input2': form.cleaned_data['input2'],
                'input3': form.cleaned_data['input3'],
                'input4': form.cleaned_data['input4'],
                'textarea': form.cleaned_data['textarea'],
                'checkbox': form.cleaned_data['checkbox'],
                'dropdown': form.cleaned_data['dropdown'],
            })
            redirect_url = redirect('filterapp:b_view').url + '?' + data
            return redirect(redirect_url)
    else:
        form = InputForm()
    return render(request, 'a.html', {'form': form})

def b_view(request):
    data = {
        'input1': request.GET.get('input1', ''),
        'input2': request.GET.get('input2', ''),
        'input3': request.GET.get('input3', ''),
        'input4': request.GET.get('input4', ''),
        'textarea': request.GET.get('textarea', ''),
        'checkbox': request.GET.get('checkbox', ''),
        'dropdown': request.GET.get('dropdown', ''),
    }
    return render(request, 'b.html', {'data': data})


def parse_ddl(ddl_statement):
    # 修改正则表达式以匹配可能在反引号中的表名
    table_name_match = re.search(r'CREATE TABLE(?: IF NOT EXISTS)? `?(\w+)`?', ddl_statement)
    table_name = table_name_match.group(1) if table_name_match else ''

    # 调整字段匹配的正则表达式，确保不匹配 IF NOT EXISTS
    fields_match = re.findall(
        r'`?(\w+)`?\s+(\w+)(?:\((\d+)\))?(?:\s+(PRIMARY KEY|FOREIGN KEY|UNIQUE|NOT NULL|AUTO_INCREMENT|IF NOT EXISTS))?', ddl_statement)

    # 过滤掉字段名为 'create' 的情况，以避免识别错误
    columns = [{'name': name, 'type': type_, 'length': int(length) if length else None,
                'constraint': constraint if constraint else ''}
               for name, type_, length, constraint in fields_match if name.lower() != 'create']

    return table_name, columns

def process_ddl(request):
    col_map = {
        "varchar": "nvarchar2",
        "int": "bigint",
        "number": "bigint"
    }

    if request.method == 'POST':
        source_system = request.POST.get('source_system', '') # 获取来源系统
        operation = request.POST.get('operation', '') # 获取操作类型（增量或全量）
        form = MySQLDDLForm(request.POST)
        if form.is_valid():
            ddl_statement = form.cleaned_data['ddl_statement']
            table_name, columns = parse_ddl(ddl_statement)
            if table_name and columns:
                # 清空旧数据
                TableInfo.objects.filter(table_name=table_name).delete()
                for column in columns:
                    type_lower = column['type'].lower()
                    # 如果找到了匹配的键，返回对应的值，否则返回空字符串
                    hive_col = col_map.get(type_lower, '')
                    if hive_col and column.get('length'):
                        hive_col += f"({column['length']})"
                    TableInfo.objects.create(
                        table_name=table_name,
                        column_name=column['name'],
                        column_type=column['type'],
                        column_length=column.get('length', ''),
                        hive_column_type=hive_col
                    )
                # 从数据库中获取字段信息并拼接 Hive 的建表语句
                table_info_objects = TableInfo.objects.filter(table_name=table_name)
                hive_columns = [f"{table_info.column_name} {table_info.hive_column_type}" for table_info in table_info_objects]
                d_table_name=f"tgf_dcl.d_{source_system}_{table_name}"
                o_table_name = f"tgf_ods.o_{source_system}_{table_name}"
                d_ddl = f"CREATE TABLE {d_table_name} (\n" + ",\n".join(hive_columns) + "\n,record_fin nvarchar2(32),\netl_timestamp timestamp,\netl_dt date)"
                o_ddl = f"CREATE TABLE {o_table_name} (\n" + ",\n".join(hive_columns) + "\n,record_fin nvarchar2(32),\nstart_dat nvarchar2(32),\nend_date nvarchar2(32),\netl_timestamp timestamp,\netl_dt date)"
                col_info = table_info_objects

                dml_col = [f"{table_info.column_name} " for table_info in table_info_objects]

                obs_info = f"ak'' \nsk '' \npath='obs/xxx/xxx/xx/';"
                d_et = f"dorp table {d_table_name}_et;\ncreate table {d_table_name}_et (\n" + ",\n".join(dml_col) +"\n);"

myblog2024010/filterapp/templates/a.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A 页面</title>
</head>
<body>
    <h1>输入内容</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">提交</button>
    </form>


</body>
</html>

myblog2024010/filterapp/templates/add_filter_info.html
{% extends "index.html" %}

{% block title %}Success{% endblock %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Filter Info</title>
</head>
<body>
    <h1>Add Filter Information</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

{% endblock %}

myblog2024010/filterapp/templates/bbout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>页面B</title>
</head>
<body>
  <h1>页面B</h1>
print({{ partition_info }})
  <!-- 显示从页面A传递过来的部分数据 -->
  <p>{{ data_to_display }}</p>

  <!-- 关闭按钮 -->
  <button onclick="goBack()">关闭</button>

  <script>
    // 返回上一页
    function goBack() {
      window.history.back();
    }
  </script>
</body>
</html>

myblog2024010/filterapp/templates/con_sql.html
<!DOCTYPE html>
<html>
<head>
    <title>Conversion Result</title>
</head>
<body>
    <h1>PostgreSQL Table Creation Script</h1>
    <pre>{{ postgresql_sql }}</pre>

    <h1>Insert Statement</h1>
    <pre>{{ insert_sql }}</pre>
</body>
</html>

myblog2024010/filterapp/templates/edit_index_etl.html
{% extends "index.html" %}

{% block title %}Success{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Index ETL</title>
</head>
<body>
    <h1>Edit Index ETL</h1>
    <form method="post">
        {% csrf_token %}
        <label for="new_sql_info">New SQL Info:</label><br>
        <textarea id="new_sql_info" name="new_sql_info" rows="5" cols="50">{{ index_etl_obj.index_no }}</textarea><br><br>

        <!-- Add other fields here -->
        <label for="new_field1">New Field 1:</label><br>
        <input type="text" id="new_field1" name="new_field1" value="{{ index_etl_obj.index_name }}"><br><br>

        <label for="new_field2">New Field 2:</label><br>
        <input type="text" id="new_field2" name="new_field2" value="{{ index_etl_obj.dep_info }}"><br><br>


        <label for="new_field3">New Field 3:</label><br>
        <input type="text" id="new_field3" name="new_field3" value="{{ index_etl_obj.sql_info }}"><br><br>
        <!-- Add more fields as needed -->

        <input type="submit" value="Update">
    </form>
</body>
{% endblock %}

myblog2024010/filterapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}我的一堆表{% endblock %}</title>
    <!-- 引入 Bootstrap CSS 文件 -->
{#    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">#}

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <style>
            /* 自定义样式 */
            .nav {
                list-style-type: none;
                margin: 0;
                padding: 0;
                text-align: center; /* 文本居中显示 */
                background-color: #262626; /* 导航栏背景色 */
                height: 60px; /* 导航栏高度 */
                line-height: 60px; /* 垂直居中 */
                font-size: 28px; /* 导航链接字体大小 */
            }
             .nav-item {
                display: inline-block; /* 导航项水平排列 */
                margin-right: 200px; /* 导航项之间的右边距 */
            }
            .nav-link {
                color: #999; /* 导航链接颜色 */
                text-decoration: none; /* 去掉下划线 */
            }
            .nav-link:hover {
                color: #fff; /* 鼠标悬停时的导航链接颜色 */
            }
            .footer {
                margin-top: 50px;
                text-align: center;
            }
        </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <ul class="navbar-nav nav mx-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'filterapp:success' %}">指标库信息</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'filterapp:display_table_info' %}">数据开发平台</a>
            </li>


            <!-- 如果您有其他导航链接，可以继续添加在这里 -->
        </ul>

    </div>
</nav>

{#<div class="container mt-3">#}
{#    <div class="float-right">#}
{#        <a href="{% url 'filterapp:add_info' %}" class="btn btn-primary">我的表</a>#}
{#    </div>#}
{#    <div class="clearfix"></div>#}
{#</div>#}

<div class="container-fluid mt-3" style="margin: 5px";>
    {% block content %}
{#        {% include 'success.html' %}#}
    {% endblock %}
</div>

<footer class="footer">
    <hr class="my-4">
    <p>优雅的下划线</p>
</footer>

<!-- 引入 Bootstrap JavaScript 文件 -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>

</body>
</html>

myblog2024010/filterapp/templates/success.html
{% extends "index.html" %}

{% block title %}Success{% endblock %}

{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Success</title>
{#    <link href="static/css/bootstrap.css" rel="stylesheet">#}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons-1.11.3/font/bootstrap-icons.css' %}" rel="stylesheet">
{#    <link href="https://cdn.bootcdn.net/ajax/libs/bootstrap-icons/1.11.0/font/bootstrap-icons.css" rel="stylesheet">#}
{# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">#}
    <!-- 引入 Bootstrap JavaScript 文件（包含 Popper.js）-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</head>

<style>
        body {
            background-color: #282C34;
            color: #ABB2BF;
            font-family: Arial, sans-serif;
            padding-top: 0px; /* 顶部间距 */
        }
        /* 自定义 CSS 样式 */
        .header-container {
            position: relative;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

         .right-aligned-link {
            margin-left: 20px; /* 可根据需要调整水平方向的间距 */
            padding: 15px 25px; /* 调整按钮的内边距，使其更大 */
            font-size: 26px; /* 调整按钮文字的大小 */
            background-color: #007bff; /* 设置按钮的背景色 */
            border-color: #ff6600; /* 设置按钮的边框颜色 */
            text-decoration: none;
        }

        .right-aligned-link:hover,
        .right-aligned-link:focus {
            background-color: #007bff; /* 设置按钮的悬停状态背景色 */
            border-color: #cc5500; /* 设置按钮的悬停状态边框颜色 */
        }


        table {
            border-collapse: collapse;
            width: 100%; /* 固定宽度 */
            table-layout: fixed; /* 固定表格布局 */
        }
        .table {
            background-color: #fff;
            color: #000; /* 表格文字颜色 */
        }

        .table th {
            background-color: #358ae8; /* Bootstrap中的默认明亮色 */
            color: #fff; /* 表头文字颜色 */
        }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f8f9fa; /* 行间隔背景色 */
        }
        th, td {
            border: 1px solid #222;
            padding: 12px;
            text-align: left; /* 文字靠左对齐 */
            vertical-align: middle; /* 内容垂直居中 */
            font-size: 18px; /* 设置字体大小为 14 像素 */
            text-align: left;
            white-space: nowrap; /* 不换行 */
            overflow: hidden;
            text-overflow: ellipsis; /* 超出部分显示省略号 */
        }
        th {
            background-color: #333;
            color: #fff;
            text-align: center; /* 表头居中 */
        }

        td {
            background-color: #ccc;
        }
        . scrollable {
            max-width: 1800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            overflow-x: auto; /* 水平滚动条 */
        }
           .tooltip {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            border: 1px solid #ccc;
            padding: 10px;
            z-index: 1;
        }

        .sql-cell:hover .tooltip {
            display: block;
        }
       .action-sql {
        width: 60%; /* 设置固定宽度，这里以 100px 为例，根据实际需求调整 */
        }
        .action-column {
        width: 140px; /* 设置固定宽度，这里以 100px 为例，根据实际需求调整 */
        }

            .btn-primary {
            background-color: rgb(170, 115, 238); /* Bootstrap中的默认蓝色 */
            border-color: #000a1a; /* 按钮边框颜色 */
            color: #dfe0e1;
        }

        .btn-primary:hover {
            background-color: #dce7ef; /* 鼠标悬停时的背景色 */
            border-color: #38026c; /* 鼠标悬停时的边框颜色 */
            color: #000;
        }

    </style>

<body>
 <div class="container-fluid mt-2">
        <div class="header-container">
            <!-- 一级标题和链接 -->
            <div class="header-content">
                <!-- 一级标题 -->
                <h1>All Filter Information</h1>

                <!-- 链接放在页面的顶部右侧 -->
                <a href="{% url 'filterapp:add_info' %}" class="btn btn-primary right-aligned-link">新增指标</a>
            </div>
        </div>
<p>Here are all the filter information that have been added:</p>
        <!-- 其他页面内容 -->
        <!-- 这里放其他内容，例如表格、图表等 -->
      <div class="scrollable">

       <table class="table table-striped">
            <tr>
                <th>指标id</th>
                <th>指标编号</th>
                <th>指标名称</th>
                <th class="action-dep">指标依赖</th>
                <th class="action-sql">技术口径</th>
                <th class="action-column">操 作</th>
                <!-- 如果有其他字段，请根据需要添加更多表头 -->
            </tr>
            {% for filter_info in etl_info_list %}
            <tr>
                <td>{{ filter_info.id }}</td>
                <td>{{ filter_info.index_no }}</td>
                <td>{{ filter_info.index_name }}</td>
                <td>{{ filter_info.dep_info }}</td>
{#                <td>{{ filter_info.sql_info }}</td>#}
                <td class="sql-info" data-toggle="modal" data-target="#exampleModal" data-sql-info="{{ filter_info.sql_info }}">{{ filter_info.sql_info }}</td>
{#                <td class="sql-info" data-toggle="modal" data-target="#exampleModal" data-sql-info="{{ filter_info.sql_info }}">{{ filter_info.short_sql_info }}</td>#}
{#                <td class="sql-cell position-relative">#}
{#                    <div class="default-content">{{ filter_info.sql_info }}</div>#}
{#                    <div class="tooltip" style="white-space: pre-wrap;">{{ filter_info.sql_info | linebreaks }}</div>#}
{#                </td>#}
                <td>
                    <a href="{% url 'filterapp:edit_info' index_id=filter_info.id %}" class="btn btn-primary"><i class="bi bi-pencil-square"></i> <!-- 笔图标 --></a>
                    <a href="{% url 'filterapp:delete_info' index_id=filter_info.id %}" class="btn btn-secondary" onclick="return confirm('确定要删除吗？')">删除</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
 </div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg">
    <div class="modal-dialog modal-dialog-scrollable modal-lg" style="max-width: 1800px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">详细内容</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="max-height: 80%;overflow-y: auto;word-wrap: break-word; overflow-wrap: break-word;">
        <pre id="fullSqlInfo"></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
  </div>
</div>

{#<script src="static/js/bootstrap.bundle.js"></script>#}
{#<script src="{% static 'js/bootstrap.bundle.js' %}"></script>#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<!-- 自定义脚本 -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const sqlCells = document.querySelectorAll('.sql-info');

    sqlCells.forEach(function(cell) {
      cell.addEventListener('click', function() {
        const sqlInfoContent = cell.textContent.trim();
        document.querySelector('#fullSqlInfo').textContent = sqlInfoContent;
        $('#exampleModal').modal('show'); // 使用 Bootstrap 的 modal 方法显示模态框
      });
    });
  });
</script>


</body>

{#<script src="{% static 'js/bootstrap.bundle.js' %}"></script>#}


{% endblock %}